### PR TITLE
Replacing `webpack` with `esbuild`.

### PR DESCRIPTION
**Pull request by erinesullivan**
# Overview
As of May 4, 2023, Tech Steering has decided that the standard JavaScript bundler for projects will be [esbuild](https://www.npmjs.com/package/esbuild). To put this into practice, `webpack` is being replaced with it.

The scripts have been constructed with the help of the [API documentation](https://esbuild.github.io/api/) and [Digital Collections Style Guide](https://github.com/mlibrary/digital-collections-style-guide/blob/main/package.json). 

## Anything else?
* `sass` is now listed under `devDependencies`.
* `npm run build` script has been added to build both `.scss` and `.js` files.
* Docker has been updated to now support `esbuild`.
* `README.md` has been updated. 

## Testing
- Rebuild the repository, and start it.
- Make changes to a `./js/.*.js` file and a `./css/*.scss` file. Check to see if the changes have been made.

### CODE REVIEW

**Review by niquerio — CHANGES_REQUESTED** [review]
Does the route "/current-checkouts/u-m-library" work for you? For me it's trying to look for `/bundles/current-checkouts-u-m-library.bundle.js` which doesn't exist.

**Comment by erinesullivan** [comment]
@niquerio The original file was named `current-checkouts.js` and not `current-checkouts-u-m-library.js`, so I changed the name.

When you run `docker-compose run --rm web npm run build` or `docker-compose run --rm web npm run build-js`, do you get this error?

```bash
sh: 1: esbuild: Exec format error
ERROR: 126
```
When I do `docker-compose up`, everything works fine and builds the files as expected whenever I make changes to the `.js` files. Running `npm run build` or `npm run build-js` also work as expected. The scripts aren't happen when trying to execute through `docker-compose`.

**Comment by niquerio** [comment]
@erinesullivan I just did a git pull and `docker-compose run --rm web npm run build` and `docker-compose run --rm web build-js` and both worked for me

**Review by niquerio — APPROVED** [review]
Looks like it's working now.

**Pull request merged**
